#!/usr/bin/env python3
"""Generate TypeScript agent API contract types from Python Pydantic contracts."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter


REPO_ROOT = Path(__file__).resolve().parents[3]
API_ROOT = REPO_ROOT / "services" / "api"
OUT_PATH = REPO_ROOT / "packages" / "api-client" / "src" / "types.generated.ts"

sys.path.insert(0, str(API_ROOT))

from api.agent_contracts import TS_EXPORTS  # noqa: E402


Schema = dict[str, Any]


def main() -> None:
    defs: dict[str, Schema] = {}
    exports: dict[str, Schema] = {}
    for name, annotation in TS_EXPORTS.items():
        schema = TypeAdapter(annotation).json_schema(ref_template="#/$defs/{model}")
        defs.update(schema.pop("$defs", {}))
        exports[name] = schema

    lines = [
        "/* eslint-disable */",
        "// Generated by packages/api-client/scripts/generate-agent-types.py.",
        "// Source of truth: services/api/api/agent_contracts.py.",
        "",
    ]

    emitted_defs: set[str] = set()
    for name, schema in defs.items():
        lines.extend(render_named_export(name, schema))
        emitted_defs.add(name)

    for name, schema in exports.items():
        if name in emitted_defs:
            continue
        lines.extend(render_named_export(name, schema))

    OUT_PATH.write_text("\n".join(lines).rstrip() + "\n")


def render_named_export(name: str, schema: Schema) -> list[str]:
    if schema.get("type") == "object" and schema.get("properties"):
        return render_interface(name, schema)
    return [f"export type {name} = {render_schema(schema)};", ""]


def render_interface(name: str, schema: Schema) -> list[str]:
    required = set(schema.get("required", []))
    lines = [f"export interface {name} {{"]
    if schema.get("additionalProperties") is True:
        lines.append("  [key: string]: unknown;")
    for prop_name, prop_schema in schema.get("properties", {}).items():
        optional = "?" if prop_name not in required else ""
        lines.append(f"  {property_key(prop_name)}{optional}: {render_schema(prop_schema)};")
    lines.append("}")
    lines.append("")
    return lines


def render_schema(schema: Schema) -> str:
    if "x-ts-type" in schema:
        return str(schema["x-ts-type"])
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(literal(value) for value in schema["enum"]) or "never"
    if "anyOf" in schema:
        return render_union(schema["anyOf"])
    if "oneOf" in schema:
        return render_union(schema["oneOf"])
    if "allOf" in schema:
        return " & ".join(render_schema(item) for item in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return render_union([{"type": item} for item in schema_type])
    if schema_type == "null":
        return "null"
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "array":
        return f"Array<{render_schema(schema.get('items', {}))}>"
    if schema_type == "object":
        properties = schema.get("properties")
        if properties:
            required = set(schema.get("required", []))
            rendered_props = []
            if schema.get("additionalProperties") is True:
                rendered_props.append("[key: string]: unknown")
            for prop_name, prop_schema in properties.items():
                optional = "?" if prop_name not in required else ""
                rendered_props.append(
                    f"{property_key(prop_name)}{optional}: {render_schema(prop_schema)}"
                )
            return "{ " + "; ".join(rendered_props) + " }"
        additional = schema.get("additionalProperties", True)
        if isinstance(additional, dict):
            return f"Record<string, {render_schema(additional)}>"
        return "Record<string, unknown>"

    return "unknown"


def render_union(items: list[Schema]) -> str:
    rendered: list[str] = []
    for item in items:
        value = render_schema(item)
        if value not in rendered:
            rendered.append(value)
    return " | ".join(rendered) or "never"


def ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def property_key(value: str) -> str:
    if re.fullmatch(r"[A-Za-z_$][A-Za-z0-9_$]*", value):
        return value
    return json.dumps(value)


def literal(value: Any) -> str:
    if value is None:
        return "null"
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return json.dumps(value)
    return str(value)


if __name__ == "__main__":
    main()
