/* eslint-disable */
// Generated by packages/api-client/scripts/generate-agent-types.py.
// Source of truth: services/api/api/agent_contracts.py.

export interface Base64Source {
  type: "base64";
  media_type: string;
  data: string;
}

export interface AttachmentRefContentBlock {
  type: "attachment_ref";
  id?: string | null;
  attachment_id?: string | null;
  name: string;
  mime_type?: string | null;
  media_type?: string | null;
  source_path?: string | null;
  source_url?: string | null;
}

export interface BinaryContentBlock {
  type: "image" | "document" | "file";
  name?: string | null;
  mime_type?: string | null;
  size?: number | null;
  slack_file_id?: string | null;
  source_path?: string | null;
  source: Base64Source;
}

export interface TextContentBlock {
  type: "text";
  text: string;
}

export interface ToolResultContentBlock {
  type: "tool_result";
  tool_use_id: string;
  content?: unknown;
  is_error?: boolean | null;
}

export interface ToolUseContentBlock {
  type: "tool_use";
  id: string;
  name: string;
  input: Record<string, unknown>;
}

export interface AgentInputMessagePayload {
  [key: string]: unknown;
  role?: "user" | "assistant" | "system" | "tool" | null;
  content: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock>;
}

export interface AgentMessageEvent {
  type: "user" | "assistant";
  message: AgentInputMessagePayload;
}

export interface BatchMessageItem {
  assignment_generation?: number | null;
  message_id?: string | null;
  event?: AgentMessageEvent | null;
  role?: "user" | "assistant" | "system" | "tool" | null;
  parts?: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock> | null;
  user_id?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface AgentDelivery {
  [key: string]: unknown;
  platform?: string | null;
  channel?: string | null;
  channel_id?: string | null;
  thread_ts?: string | null;
  recipient_user_id?: string | null;
  recipient_team_id?: string | null;
}

export interface ThreadExecutionSummary {
  execution_id: string;
  execute_id: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
}

export interface ReleaseThreadResultNotReleased {
  ok: true;
  thread_key: string;
  released: false;
  reason: string;
}

export interface ReleaseThreadResultReleased {
  ok: true;
  thread_key: string;
  released: true;
  assignment_generation: number;
  runtime_id: string;
}

export interface AgentStatusActiveAssignment {
  assignment_generation: number;
  runtime_id: string;
  harness: string;
  persona_id?: string | null;
  prompt_ref?: string | null;
  effective_agents_md_sha256?: string | null;
  state: string;
}

export interface AgentRepoContext {
  cwd?: string | null;
  repo_owner?: string | null;
  repo_name?: string | null;
  git_ref?: string | null;
  git_commit?: string | null;
}

export interface FinalDeliveryPayload {
  [key: string]: unknown;
  execution_id?: string | null;
  thread_key?: string | null;
  status?: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled" | null;
  terminal_reason?: "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded" | null;
  session_title?: string | null;
  session_header?: string | null;
  result_text?: string | null;
  result?: string | null;
  text?: string | null;
  final_text?: string | null;
  message?: string | null;
  error_text?: string | null;
  slackbot_streamed_answer_chars?: number | null;
  agent_thread_id?: string | null;
  repo_context?: AgentRepoContext | null;
  suppress_final_delivery?: boolean | null;
}

export interface FinalDeliveryRecord {
  execution_id: string;
  thread_key: string;
  trace_id?: string | null;
  traceparent?: string | null;
  attempt_count: number;
  delivery?: AgentDelivery | null;
  final_payload?: FinalDeliveryPayload | null;
}

export interface AgentAssistantStreamEvent {
  [key: string]: unknown;
  type: "assistant";
  message: AgentMessagePayload;
}

export interface AgentCommandExecutionStreamEvent {
  [key: string]: unknown;
  type: "command_execution";
  command?: string | null;
  aggregated_output?: string | null;
  exit_code?: number | string | null;
  status?: string | null;
}

export interface AgentErrorStreamEvent {
  [key: string]: unknown;
  type: "error";
  error: string;
}

export interface AgentExecutionStateEvent {
  [key: string]: unknown;
  type: "execution.state";
  execution_id: string;
  thread_key: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  terminal_reason?: "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded" | null;
  result_text?: string | null;
  error_text?: string | null;
  agent_thread_id?: string | null;
  repo_context?: AgentRepoContext | null;
  suppress_final_delivery?: boolean | null;
}

export interface AgentFileChangeStreamEvent {
  [key: string]: unknown;
  type: "file_change";
  changes: Array<Record<string, unknown>>;
}

export interface AgentMessagePayload {
  [key: string]: unknown;
  role?: "user" | "assistant" | "system" | "tool" | null;
  content: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock | ToolUseContentBlock | ToolResultContentBlock> | string;
  usage?: Record<string, unknown> | null;
  model?: string | null;
}

export interface AgentReasoningStreamEvent {
  [key: string]: unknown;
  type: "reasoning";
  text: string;
}

export interface AgentResultStreamEvent {
  [key: string]: unknown;
  type: "result";
  text?: string | null;
  result?: string | null;
  result_text?: string | null;
  error?: string | null;
  is_error?: boolean | null;
}

export interface AgentSubagentActivity {
  description: string;
  toolName?: string | null;
}

export interface AgentSubagentStreamEvent {
  [key: string]: unknown;
  type: "subagent";
  status: string;
  subagent_id: string;
  name?: string | null;
  summary?: string | null;
  error?: string | null;
  activity?: string | null;
  activities?: Array<AgentSubagentActivity> | null;
}

export interface AgentSystemStreamEvent {
  [key: string]: unknown;
  type: "system" | "session" | "thread.started";
  subtype?: string | null;
  session_id?: string | null;
  thread_id?: string | null;
}

export interface AgentToolStreamEvent {
  [key: string]: unknown;
  type: "tool";
  content: Array<ToolResultEntry>;
}

export interface AgentTurnDoneStreamEvent {
  [key: string]: unknown;
  type: "turn.done" | "turn.completed";
  turn_id?: number | null;
  result?: string | null;
  result_text?: string | null;
  text?: string | null;
  error?: string | null;
  is_error?: boolean | null;
  repo_context?: AgentRepoContext | null;
}

export interface AgentUsageStreamEvent {
  [key: string]: unknown;
  type: "usage";
  usage: Record<string, unknown>;
  model?: string | null;
  authoritative?: boolean | null;
}

export interface AgentUserStreamEvent {
  [key: string]: unknown;
  type: "user";
  message?: AgentMessagePayload | null;
  content?: Array<ToolResultEntry> | null;
}

export interface CodexPassthroughStreamEvent {
  [key: string]: unknown;
  type: "turn.plan.updated" | "item.started" | "item.updated" | "item.completed" | "item.agentMessage.delta" | "item.plan.delta" | "item.commandExecution.outputDelta" | "item.fileChange.outputDelta" | "item.fileChange.patchUpdated" | "item.reasoning.summaryTextDelta" | "item.reasoning.summaryPartAdded" | "item.reasoning.textDelta";
}

export interface ExecutionSummaryStreamEvent {
  [key: string]: unknown;
  type: "execution.summary";
  execution_id: string;
  thread_key: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  terminal_reason?: "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded" | null;
}

export interface FinalDeliveryDeliveredEvent {
  [key: string]: unknown;
  type: "final_delivery.delivered";
  execution_id: string;
  thread_key: string;
}

export interface FinalDeliveryReadyEvent {
  [key: string]: unknown;
  execution_id: string;
  thread_key: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  terminal_reason?: "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded" | null;
  session_title?: string | null;
  session_header?: string | null;
  result_text?: string | null;
  result?: string | null;
  text?: string | null;
  final_text?: string | null;
  message?: string | null;
  error_text?: string | null;
  slackbot_streamed_answer_chars?: number | null;
  agent_thread_id?: string | null;
  repo_context?: AgentRepoContext | null;
  suppress_final_delivery?: boolean | null;
  type: "final_delivery.ready";
}

export interface ObservationStreamEvent {
  [key: string]: unknown;
  type: `obs.${string}`;
  execution_id?: string | null;
  thread_key?: string | null;
}

export interface ToolResultEntry {
  tool_use_id: string;
  content?: unknown;
  is_error?: boolean | null;
}

export interface UnknownStreamData {
  [key: string]: unknown;
  type: "unknown";
  raw: string;
}

export type AgentMessageRole = "user" | "assistant" | "system" | "tool";

export type AgentExecutionStatus = "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";

export type AgentTerminalReason = "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded";

export type AgentInputContentBlock = TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock;

export type AgentContentBlock = TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock | ToolUseContentBlock | ToolResultContentBlock;

export interface SpawnRequest {
  thread_key: string;
  spawn_id?: string | null;
  harness?: string | null;
  engine?: string | null;
  persona_id?: string | null;
  agents_md_override?: string | null;
}

export interface SpawnResult {
  ok: boolean;
  runtime_id: string;
  thread_key: string;
  trace_id?: string | null;
  assignment_state: string;
  assignment_generation: number;
  persona_id?: string | null;
  prompt_ref?: string | null;
  effective_agents_md_sha256?: string | null;
}

export interface MessageRequest {
  thread_key: string;
  assignment_generation: number;
  message_id?: string | null;
  event?: AgentMessageEvent | null;
  role?: "user" | "assistant" | "system" | "tool" | null;
  parts?: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock> | null;
  user_id?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface MessageAccepted {
  ok: boolean;
  message_id: string;
  stored_event_id?: string | null;
  attachment_ids: Array<string>;
  idempotent?: boolean | null;
}

export interface BatchMessageRequest {
  thread_key: string;
  assignment_generation: number;
  message_id?: string | null;
  event?: AgentMessageEvent | null;
  role?: "user" | "assistant" | "system" | "tool" | null;
  parts?: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock> | null;
  user_id?: string | null;
  metadata?: Record<string, unknown> | null;
  messages?: Array<BatchMessageItem> | null;
}

export interface BatchMessageAccepted {
  ok: boolean;
  inserted: number;
  message_ids: Array<string>;
}

export interface ExecuteRequest {
  thread_key: string;
  assignment_generation?: number | null;
  execute_id?: string | null;
  harness?: string | null;
  delivery?: AgentDelivery | null;
  platform?: string | null;
  user_id?: string | null;
  metadata?: Record<string, unknown> | null;
  message?: string | null;
  engine?: string | null;
  persona_id?: string | null;
}

export interface ExecutionAccepted {
  ok: boolean;
  execution_id: string;
  execute_id: string;
  assignment_generation: number;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  final_key: string;
  delivery_token: string;
  idempotent?: boolean | null;
}

export interface SteerExecutionRequest {
  content_blocks?: Array<TextContentBlock | BinaryContentBlock | AttachmentRefContentBlock> | null;
  message_id?: string | null;
  user_id?: string | null;
  metadata?: Record<string, unknown> | null;
}

export interface AgentExecutionRecord {
  [key: string]: unknown;
  execution_id: string;
  thread_key: string;
  assignment_generation: number;
  execute_id: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled";
  durable_turn_id?: string | null;
  terminal_reason?: "completed" | "cancel_requested" | "cancelled" | "released" | "harness_error" | "harness_auth_failed" | "amp_reconnect_timeout" | "assignment_missing" | "execution_error" | "stream_ended_without_turn_done" | "hard_deadline_exceeded" | "silence_deadline_exceeded" | null;
  result_text?: string | null;
  error_text?: string | null;
  agent_thread_id: string;
  metadata: Record<string, unknown>;
  created_at?: string | null;
  started_at?: string | null;
  completed_at?: string | null;
  updated_at?: string | null;
}

export interface ThreadExecutionList {
  thread_key: string;
  executions: Array<ThreadExecutionSummary>;
}

export interface ExecutionControlResult {
  ok: boolean;
  execution_id: string;
  thread_key: string;
  status: "queued" | "running" | "retry_wait" | "cancel_requested" | "completed" | "failed_permanent" | "cancelled" | "steered";
  idempotent?: boolean | null;
}

export interface ReleaseRequest {
  release_id?: string | null;
  cancel_inflight?: boolean;
}

export type ReleaseThreadResult = ReleaseThreadResultReleased | ReleaseThreadResultNotReleased;

export interface AgentStatus {
  [key: string]: unknown;
  thread_key?: string | null;
  state?: string | null;
  harness?: string | null;
  engine?: string | null;
  pending_messages?: number | null;
  last_result?: string | null;
  active_assignment?: AgentStatusActiveAssignment | null;
}

export interface FinalDeliveryClaimResponse {
  deliveries: Array<FinalDeliveryRecord>;
}

export interface FinalDeliveryMutationResult {
  ok: boolean;
  execution_id: string;
  idempotent?: boolean | null;
}

export interface ClaimFinalDeliveryRequest {
  consumer_id: string;
  limit?: number;
  lease_seconds?: number;
  platform?: string | null;
}

export interface RenewFinalDeliveryLeaseRequest {
  consumer_id: string;
  lease_seconds?: number;
}

export interface MarkFinalDeliveredRequest {
  consumer_id?: string | null;
}

export interface MarkFinalFailedRequest {
  consumer_id?: string | null;
  error: string;
  retry_after_seconds?: number;
  non_retryable?: boolean;
  error_class?: string | null;
}

export type AgentStreamData = AgentAssistantStreamEvent | AgentUserStreamEvent | AgentToolStreamEvent | AgentReasoningStreamEvent | AgentCommandExecutionStreamEvent | AgentFileChangeStreamEvent | AgentSubagentStreamEvent | AgentResultStreamEvent | AgentErrorStreamEvent | AgentSystemStreamEvent | AgentUsageStreamEvent | AgentTurnDoneStreamEvent | AgentExecutionStateEvent | FinalDeliveryReadyEvent | FinalDeliveryDeliveredEvent | CodexPassthroughStreamEvent | ObservationStreamEvent | ExecutionSummaryStreamEvent | UnknownStreamData;

export type AgentStreamEventKind = "amp_raw_event" | "execution_state" | "execution_started" | "execution_summary" | "final_delivery_ready" | "final_delivery_delivered" | "assistant_message_observed" | "assistant_text_observed" | "assistant_tool_use_observed" | "tool_result_observed" | "reasoning_observed" | "command_observed" | "file_change_observed" | "subagent_status_observed" | "usage_observed" | "result_observed" | "error_observed" | "message";

export interface StreamEvent {
  eventId: number;
  eventKind: "amp_raw_event" | "execution_state" | "execution_started" | "execution_summary" | "final_delivery_ready" | "final_delivery_delivered" | "assistant_message_observed" | "assistant_text_observed" | "assistant_tool_use_observed" | "tool_result_observed" | "reasoning_observed" | "command_observed" | "file_change_observed" | "subagent_status_observed" | "usage_observed" | "result_observed" | "error_observed" | "message" | string;
  data: AgentAssistantStreamEvent | AgentUserStreamEvent | AgentToolStreamEvent | AgentReasoningStreamEvent | AgentCommandExecutionStreamEvent | AgentFileChangeStreamEvent | AgentSubagentStreamEvent | AgentResultStreamEvent | AgentErrorStreamEvent | AgentSystemStreamEvent | AgentUsageStreamEvent | AgentTurnDoneStreamEvent | AgentExecutionStateEvent | FinalDeliveryReadyEvent | FinalDeliveryDeliveredEvent | CodexPassthroughStreamEvent | ObservationStreamEvent | ExecutionSummaryStreamEvent | UnknownStreamData;
}
